let
    Source = Csv.Document(File.Contents("C:\Users\Samsung\Documents\Curso PBI Claudio Bonel\BaseDPEvolucaoMensalCisp.csv"),[Delimiter=";", Columns=63, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}, {"Column5", type text}, {"Column6", type text}, {"Column7", type text}, {"Column8", type text}, {"Column9", type text}, {"Column10", type text}, {"Column11", type text}, {"Column12", type text}, {"Column13", type text}, {"Column14", type text}, {"Column15", type text}, {"Column16", type text}, {"Column17", type text}, {"Column18", type text}, {"Column19", type text}, {"Column20", type text}, {"Column21", type text}, {"Column22", type text}, {"Column23", type text}, {"Column24", type text}, {"Column25", type text}, {"Column26", type text}, {"Column27", type text}, {"Column28", type text}, {"Column29", type text}, {"Column30", type text}, {"Column31", type text}, {"Column32", type text}, {"Column33", type text}, {"Column34", type text}, {"Column35", type text}, {"Column36", type text}, {"Column37", type text}, {"Column38", type text}, {"Column39", type text}, {"Column40", type text}, {"Column41", type text}, {"Column42", type text}, {"Column43", type text}, {"Column44", type text}, {"Column45", type text}, {"Column46", type text}, {"Column47", type text}, {"Column48", type text}, {"Column49", type text}, {"Column50", type text}, {"Column51", type text}, {"Column52", type text}, {"Column53", type text}, {"Column54", type text}, {"Column55", type text}, {"Column56", type text}, {"Column57", type text}, {"Column58", type text}, {"Column59", type text}, {"Column60", type text}, {"Column61", type text}, {"Column62", type text}, {"Column63", type text}}),
    #"Remoção do cabeçalho do ERP 15032019" = Table.Skip(#"Changed Type",5),
    #"Removed Blank Rows" = Table.SelectRows(#"Remoção do cabeçalho do ERP 15032019", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Promoted Headers" = Table.PromoteHeaders(#"Removed Blank Rows", [PromoteAllScalars=true]),
    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"CISP", Int64.Type}, {"mes", Int64.Type}, {"vano", Int64.Type}, {"mes_ano", type text}, {"AISP", Int64.Type}, {"RISP", Int64.Type}, {"munic", type text}, {"mcirc", Int64.Type}, {"Regiao", type text}, {"hom_doloso", Int64.Type}, {"lesao_corp_morte", Int64.Type}, {"latrocinio", Int64.Type}, {"hom_por_interv_policial", Int64.Type}, {"tentat_hom", Int64.Type}, {"lesao_corp_dolosa", Int64.Type}, {"estupro", Int64.Type}, {"hom_culposo", Int64.Type}, {"lesao_corp_culposa", Int64.Type}, {"roubo_comercio", Int64.Type}, {"roubo_residencia", Int64.Type}, {"roubo_veiculo", Int64.Type}, {"roubo_carga", Int64.Type}, {"roubo_transeunte", Int64.Type}, {"roubo_em_coletivo", Int64.Type}, {"roubo_banco", Int64.Type}, {"roubo_cx_eletronico", Int64.Type}, {"roubo_celular", Int64.Type}, {"roubo_conducao_saque", Int64.Type}, {"roubo_apos_saque", Int64.Type}, {"roubo_bicicleta", type text}, {"outros_roubos", Int64.Type}, {"total_roubos", Int64.Type}, {"furto_veiculos", Int64.Type}, {"furto_transeunte", Int64.Type}, {"furto_coletivo", Int64.Type}, {"furto_celular", Int64.Type}, {"furto_bicicleta", type text}, {"outros_furtos", Int64.Type}, {"total_furtos", Int64.Type}, {"sequestro", Int64.Type}, {"extorsao", Int64.Type}, {"sequestro_relampago", Int64.Type}, {"estelionato", Int64.Type}, {"apreensao_drogas", Int64.Type}, {"posse_drogas", type text}, {"trafico_drogas", type text}, {"apreensao_drogas_sem_autor", type text}, {"recuperacao_veiculos", Int64.Type}, {"apf", type text}, {"aaapai", type text}, {"cmp", type text}, {"cmba", type text}, {"ameaca", Int64.Type}, {"pessoas_desaparecidas", Int64.Type}, {"encontro_cadaver", Int64.Type}, {"encontro_ossada", Int64.Type}, {"pol_militares_mortos_serv", Int64.Type}, {"pol_civis_mortos_serv", Int64.Type}, {"indicador_letalidade", Int64.Type}, {"indicador_roubo_rua", Int64.Type}, {"indicador_roubo_veic", Int64.Type}, {"registro_ocorrencias", Int64.Type}, {"fase", Int64.Type}}),
    #"Renamed Columns" = Table.RenameColumns(#"Changed Type1",{{"mcirc", "Cod_Munic_IBGE"}}),
    #"Changed Type2" = Table.TransformColumnTypes(#"Renamed Columns",{{"roubo_bicicleta", Int64.Type}, {"posse_drogas", Int64.Type}, {"trafico_drogas", Int64.Type}, {"apreensao_drogas_sem_autor", Int64.Type}, {"apf", Int64.Type}, {"aaapai", Int64.Type}, {"cmp", Int64.Type}, {"cmba", Int64.Type}}),
    #"Filtered Rows" = Table.SelectRows(#"Changed Type2", each [vano] >= 2015),
    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"CISP", "mes_ano", "AISP", "munic", "Cod_Munic_IBGE", "Regiao", "hom_doloso", "lesao_corp_morte", "latrocinio", "hom_por_interv_policial", "tentat_hom", "lesao_corp_dolosa", "estupro", "hom_culposo", "lesao_corp_culposa", "roubo_comercio", "roubo_residencia", "roubo_veiculo", "roubo_carga", "roubo_transeunte", "roubo_em_coletivo", "roubo_banco", "roubo_cx_eletronico", "roubo_celular", "roubo_conducao_saque", "roubo_apos_saque", "roubo_bicicleta", "outros_roubos", "furto_veiculos", "furto_transeunte", "furto_coletivo", "furto_celular", "furto_bicicleta", "outros_furtos", "sequestro", "extorsao", "sequestro_relampago", "estelionato", "apreensao_drogas", "posse_drogas", "trafico_drogas", "apreensao_drogas_sem_autor", "recuperacao_veiculos", "apf", "aaapai", "cmp", "cmba", "ameaca", "pessoas_desaparecidas", "encontro_cadaver", "encontro_ossada", "pol_militares_mortos_serv", "pol_civis_mortos_serv"}),
    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Other Columns", {"CISP", "mes_ano", "AISP", "munic", "Cod_Munic_IBGE", "Regiao"}, "Ocorrencias", "Qtde")
in
    #"Unpivoted Columns"